integrations:
- integration_type: git_repo
  git_repo: mosaicml/examples
  git_branch: eval_mmlu # use your branch
  # git_commit: # OR use your commit hash
  pip_install: -e .[llm]
  ssh_clone: false # Should be true if using a private repo

command: |
  cd examples/examples/llm/icl_eval
  composer evaluate_model.py /mnt/config/parameters.yaml

image: mosaicml/pytorch:1.13.1_cu117-python3.10-ubuntu20.04

# Mosaic Cloud will use run_name (with a unique suffix) to populate the env var $COMPOSER_RUN_NAME
run_name: gpt-j-eval

gpu_num: 8
gpu_type: a100_80gb
cluster: r1z1 # replace with your cluster here!

# The below is injected as a YAML file: /mnt/config/parameters.yaml
parameters:
  # Tokenizer
  tokenizer:
      name: EleutherAI/gpt-j-6b
      kwargs:
        model_max_length: 2048

  model:
    name: hf_causal_lm
    pretrained_model_name_or_path: EleutherAI/gpt-j-6b
    device: cpu
    pretrained: true


  # FSDP config for model sharding
  # fsdp_config:
  #   sharding_strategy: FULL_SHARD
  #   mixed_precision: PURE

  icl_tasks:
    -
      label: lambada_openai
      dataset_uri: local_data/lambada_openai.jsonl 
      num_fewshot:
      - 0
      batch_size: 4
      icl_task_type: language_modeling
      metric_names:
      - InContextLearningLMAccuracy
      - InContextLearningLMExpectedCalibrationError
      prompt_string: '' # this goes at the beginning of each input
      example_delimiter: '\n' # this goes between fewshot examples
      continuation_delimiter: ' ' # this separates contexts from continuations
    -
      label: piqa
      dataset_uri:  local_data/piqa.jsonl  # ADD YOUR OWN DATASET URI
      num_fewshot:
      - 0
      - 1
      - 5
      - 10
      batch_size: 4
      icl_task_type: multiple_choice
      metric_names:
      - InContextLearningMultipleChoiceAccuracy
      - InContextLearningMCExpectedCalibrationError
      prompt_string: '' # this goes at the beginning of each input
      example_delimiter: '\n' # this goes between fewshot examples
      continuation_delimiter: 'Answer: ' # this separates questions from answers
    -
      label: hellaswag
      dataset_uri: local_data/hellaswag.jsonl # ADD YOUR OWN DATASET URI
      num_fewshot:
      - 0
      - 1
      - 5
      - 10
      batch_size: 4
      icl_task_type: multiple_choice
      metric_names:
      - InContextLearningMultipleChoiceAccuracy
      - InContextLearningMCExpectedCalibrationError
      prompt_string: '' # this goes at the beginning of each input
      example_delimiter: '\n' # this goes between fewshot examples
      continuation_delimiter: ' ' # this separates questions from answers
    -
      label: arc_easy
      dataset_uri: local_data/arc_easy.jsonl # ADD YOUR OWN DATASET URI
      num_fewshot:
      - 0
      - 1
      - 5
      - 10
      batch_size: 4
      icl_task_type: multiple_choice
      metric_names:
      - InContextLearningMultipleChoiceAccuracy
      - InContextLearningMCExpectedCalibrationError

      prompt_string: '' # this goes at the beginning of each input
      example_delimiter: '\n' # this goes between fewshot examples
      continuation_delimiter: 'Answer: ' # this separates questions from answers
    -
      label: copa
      dataset_uri: local_data/copa.jsonl # ADD YOUR OWN DATASET URI
      num_fewshot:
      - 0
      - 1
      - 5
      - 10
      batch_size: 4
      icl_task_type: multiple_choice
      metric_names:
      - InContextLearningMultipleChoiceAccuracy
      - InContextLearningMCExpectedCalibrationError

      prompt_string: '' # this goes at the beginning of each input
      example_delimiter: '\n' # this goes between fewshot examples
      continuation_delimiter: ' ' # this separates questions from answers
    -
      label: boolq
      dataset_uri: local_data/boolq.jsonl # ADD YOUR OWN DATASET URI
      num_fewshot:
      - 0
      - 1
      - 5
      - 10
      batch_size: 4
      icl_task_type: multiple_choice
      metric_names:
      - InContextLearningMultipleChoiceAccuracy
      - InContextLearningMCExpectedCalibrationError
      prompt_string: '' # this goes at the beginning of each input
      example_delimiter: '\n' # this goes between fewshot examples
      continuation_delimiter: 'Answer: ' # this separates questions from answers
    -
      label: jeopardy
      dataset_uri: local_data/jeopardy_all.jsonl # ADD YOUR OWN DATASET URI
      num_fewshot:
      - 0
      - 1
      - 5
      - 10
      batch_size: 4
      icl_task_type: language_modeling
      metric_names:
      - InContextLearningLMAccuracy
      - InContextLearningLMExpectedCalibrationError
      prompt_string: '' # this goes at the beginning of each input
      example_delimiter: '\n' # this goes between fewshot examples
      continuation_delimiter: ' Answer: ' # this separates questions from answers
      has_categories: true
    -
      label: mmlu
      dataset_uri: local_data/mmlu.jsonl # ADD YOUR OWN DATASET URI
      num_fewshot:
      - 0
      - 1
      - 5
      - 10
      batch_size: 4
      icl_task_type: multiple_choice
      metric_names:
      - InContextLearningMultipleChoiceAccuracy
      - InContextLearningMCExpectedCalibrationError
      prompt_string: '' # this goes at the beginning of each input
      example_delimiter: '\n' # this goes between fewshot examples
      continuation_delimiter: 'Answer: ' # this separates questions from answers
      has_categories: true
    -
      label: winograd
      dataset_uri: local_data/winograd_wsc.jsonl # ADD YOUR OWN DATASET URI
      num_fewshot:
      - 0
      - 1
      - 5
      - 10
      batch_size: 4
      icl_task_type: schema
      metric_names:
      - InContextLearningMultipleChoiceAccuracy
      - InContextLearningMCExpectedCalibrationError
      prompt_string: '' # this goes at the beginning of each input
      example_delimiter: '\n' # this goes between fewshot examples
      continuation_delimiter: '' # this separates questions from answers
    -
      label: winogrande
      dataset_uri: local_data/winogrande.jsonl # ADD YOUR OWN DATASET URI
      num_fewshot:
      - 0
      - 1
      - 5
      - 10
      batch_size: 4
      icl_task_type: schema
      metric_names:
      - InContextLearningMultipleChoiceAccuracy
      - InContextLearningMCExpectedCalibrationError
      prompt_string: '' # this goes at the beginning of each input
      example_delimiter: '\n' # this goes between fewshot examples
      continuation_delimiter: '' # this separates questions from answers
    -
      label: triviaqa
      dataset_uri: local_data/triviaqa.jsonl # ADD YOUR OWN DATASET URI
      num_fewshot:
      - 0
      - 1
      - 5
      - 10
      batch_size: 4
      icl_task_type: question_answering
      metric_names:
      - InContextLearningQAAccuracy
      prompt_string: '' # this goes at the beginning of each input
      example_delimiter: '\n' # this goes between fewshot examples
      continuation_delimiter: ' ' # this separates questions from answers
